run:
  timeout: 5m
output:
  format: colored-line-number
  print-issued-lines: true
  print-linter-name: true
  sort-results: true
linters:
  enable-all: true
  disable:
    - deadcode
    - exhaustivestruct
    - exhaustruct
    - gochecknoglobals
    - gofmt
    - gofumpt
    - gci
    - golint
    - ifshort
    - interfacer
    - maligned
    - nlreturn
    - noctx
    - nosnakecase
    - paralleltest 
    - rowserrcheck
    - scopelint
    - sqlclosecheck
    - structcheck
    - varcheck
    - wastedassign
    - wrapcheck
    - wsl